stages:
  - test
  - deploy

before_script:
  - sudo apt-get install software-properties-common -y
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update -y
  - sudo apt-get install python3.8 python3.8-dev python3.8-venv python3-pip python3-venv python-enchant -y
  - python3.8 -mvenv ../myenv
  - source ../myenv/bin/activate
  - python3.8 -mpip install --upgrade  pip
  - python3.8 -mpip install -U sphinx sphinx-aimms-theme sphinx-sitemap sphinx-last-updated-by-git sphinxcontrib-bibtex sphinxcontrib-spelling

linkcheck:
  stage: test
  script:
  - python3 -msphinx -W --keep-going -b linkcheck . _build/linkcheck
  allow_failure: true
  tags: 
    - ubuntu
  retry: 1

spellcheck:
  stage: test
  script:
  - python3 -msphinx -W --keep-going -b spelling . _build/spelling
  allow_failure: true
  tags: 
    - ubuntu

build:
  stage: test
  script:
    - sphinx-build -W -b html . _build/html 
  tags: 
    - ubuntu

build_and_staging:
  stage: build
  script:
    - sphinx-build -M html . _build
    - ssh support@data.aimms.com mkdir -p /home/aimms/www/how-to.aimms.com/staging/${CI_COMMIT_BRANCH}
    - rsync -rt --delete-excluded _build/html/ support@data.aimms.com:/home/aimms/www/how-to.aimms.com/staging/${CI_COMMIT_BRANCH}
  tags: 
    - ubuntu
  except:
    - master

build_and_deploy:
  stage: deploy
  script:
    - sphinx-build -b html . _build/html 
    - rsync -rt _build/html/ support@data.aimms.com:/home/aimms/www/how-to.aimms.com
  tags: 
    - ubuntu
  only:
    - master
  retry: 1
